version: "3"
services:
  api-financeiro:
    image: api-financeiro
    container_name: api-financeiro
    ports:
      - "3000:3000"
    depends_on:
      - amanda
  amanda:  
    image: amanda 
    container_name: amanda
    environment: 
      ENV POSTGRES_USER: 'admin'
      ENV POSTGRES_PASSWORD: '= 123456'
      ENV POSTGRES_DB: 'amanda'
    ports:
      - "5434:5432"
    